version: "3"
services:
  web:
    build:
      context: .
      dockerfile: .docker/${APP_ENV:-development}.dockerfile
    ports:
      - 3000:3000
    env_file: .env/${APP_ENV:-development}.env
    volumes:
      - .:/var/www/id8-web
